export interface PlatformFingerprint {
  name: string;
  category: 'event' | 'webinar' | 'both';
  domains: string[];
  scriptPatterns: string[];
  networkDomains: string[];
  cookiePatterns: string[];
  globalPatterns: string[];
  formActionPatterns: string[];
  cnamePatterns: string[];
  htmlPatterns: string[];
  metaPatterns: string[];
  secondary?: boolean;
}

export const PLATFORM_FINGERPRINTS: PlatformFingerprint[] = [
  {
    name: 'Cvent',
    category: 'both',
    domains: ['cvent.com', 'web.cvent.com', 'www.cvent.com', 'guest.cvent.com', 'cvent.me'],
    scriptPatterns: [
      'cvent.com/scripts',
      'cvent.com/assets',
      'cvent-',
      'cventresource',
      'socialtables.com',
      'cvent.min.',
      'cventcdn',
      'cvt_',
      'CventOnline',
    ],
    networkDomains: [
      'api.cvent.com',
      'web.cvent.com',
      'guest.cvent.com',
      'svc.cvent.com',
      'custom.cvent.com',
      'images.cvent.com',
      'socialtables.com',
      'cventcdn.com',
    ],
    cookiePatterns: ['cvent', 'cv_', 'cvt_', 'cvent_session', 'CventSessionId', 'cvt_ref'],
    globalPatterns: ['cvent', 'CventAnalytics', 'cvt', 'CventOnline', '__cvent'],
    formActionPatterns: ['cvent.com', 'guest.cvent.com'],
    cnamePatterns: ['cvent.com', 'cvent-dns'],
    htmlPatterns: ['cvent-', 'cv-event', 'cvent_', 'cvt-'],
    metaPatterns: ['cvent', 'powered by cvent'],
  },
  {
    name: 'RainFocus',
    category: 'event',
    domains: ['rainfocus.com', 'reg.rainfocus.com'],
    scriptPatterns: ['rainfocus.com', 'rainfocus', 'rf-widget', 'rfwidget', 'rainfocus.min', 'rf_'],
    networkDomains: ['api.rainfocus.com', 'reg.rainfocus.com', 'rainfocus.com/widget', 'rainfocus.com/api', 'cdn.rainfocus.com'],
    cookiePatterns: ['rf_', 'rainfocus', 'rftoken', 'rf_session', 'rfSessionId'],
    globalPatterns: ['rainfocus', 'RainFocus', 'rfWidget', '__rf', 'RF_CONFIG'],
    formActionPatterns: ['rainfocus.com', 'reg.rainfocus.com'],
    cnamePatterns: ['rainfocus.com'],
    htmlPatterns: ['rf-', 'rainfocus-', 'rf_widget'],
    metaPatterns: ['rainfocus'],
  },
  {
    name: 'ON24',
    category: 'webinar',
    domains: ['on24.com', 'event.on24.com', 'gateway.on24.com'],
    scriptPatterns: ['on24.com', 'on24', 'on24-'],
    networkDomains: ['on24.com', 'event.on24.com', 'gateway.on24.com'],
    cookiePatterns: ['on24', 'on24_', 'on24session'],
    globalPatterns: ['ON24', 'on24'],
    formActionPatterns: ['on24.com'],
    cnamePatterns: ['on24.com'],
    htmlPatterns: ['on24', 'webcast'],
    metaPatterns: ['on24'],
  },
  {
    name: 'Bizzabo',
    category: 'event',
    domains: ['bizzabo.com', 'events.bizzabo.com'],
    scriptPatterns: ['bizzabo.com', 'bizzabo', 'bizzabo.min', 'bzb-', 'bizzabocdn'],
    networkDomains: ['api.bizzabo.com', 'events.bizzabo.com', 'rest.bizzabo.com', 'cdn.bizzabo.com', 'analytics.bizzabo.com'],
    cookiePatterns: ['bizzabo', 'bzb_', 'bizzabo_session'],
    globalPatterns: ['bizzabo', 'Bizzabo', '__bizzabo'],
    formActionPatterns: ['bizzabo.com'],
    cnamePatterns: ['bizzabo.com'],
    htmlPatterns: ['bizzabo-', 'bzb-'],
    metaPatterns: ['bizzabo'],
  },
  {
    name: 'Swoogo',
    category: 'event',
    domains: ['swoogo.com', 'app.swoogo.com'],
    scriptPatterns: ['swoogo.com', 'swoogo', 'swoogo.min'],
    networkDomains: ['api.swoogo.com', 'app.swoogo.com', 'cdn.swoogo.com'],
    cookiePatterns: ['swoogo', 'swg_'],
    globalPatterns: ['swoogo', 'Swoogo'],
    formActionPatterns: ['swoogo.com'],
    cnamePatterns: ['swoogo.com'],
    htmlPatterns: ['swoogo-'],
    metaPatterns: ['swoogo'],
  },
  {
    name: 'Splash',
    category: 'event',
    domains: ['splashthat.com', 'splash.events'],
    scriptPatterns: ['splashthat.com', 'splash-', 'splashthat'],
    networkDomains: ['api.splashthat.com', 'splashthat.com'],
    cookiePatterns: ['splash_', 'splashthat'],
    globalPatterns: ['Splash', 'splashthat'],
    formActionPatterns: ['splashthat.com'],
    cnamePatterns: ['splashthat.com'],
    htmlPatterns: ['splash-event', 'splashthat'],
    metaPatterns: ['splashthat', 'splash'],
  },
  {
    name: 'Eventbrite',
    category: 'event',
    domains: ['eventbrite.com', 'eventbrite.co.uk'],
    scriptPatterns: ['eventbrite.com', 'eventbrite', 'eb_'],
    networkDomains: ['www.eventbrite.com', 'api.eventbrite.com', 'cdn.eventbrite.com'],
    cookiePatterns: ['eventbrite', 'eb_', 'ebEventId'],
    globalPatterns: ['eventbrite', 'Eventbrite', 'EB'],
    formActionPatterns: ['eventbrite.com'],
    cnamePatterns: ['eventbrite.com'],
    htmlPatterns: ['eventbrite-'],
    metaPatterns: ['eventbrite'],
  },
  {
    name: 'Hopin',
    category: 'event',
    domains: ['hopin.com', 'app.hopin.com', 'hopin.to'],
    scriptPatterns: ['hopin.com', 'hopin', 'hopin-'],
    networkDomains: ['api.hopin.com', 'app.hopin.com', 'hopin.com'],
    cookiePatterns: ['hopin', '_hopin'],
    globalPatterns: ['Hopin', 'hopin'],
    formActionPatterns: ['hopin.com'],
    cnamePatterns: ['hopin.com', 'hopin.to'],
    htmlPatterns: ['hopin-'],
    metaPatterns: ['hopin'],
  },
  {
    name: 'Bevy',
    category: 'event',
    domains: ['bevy.com', 'bevylabs.com'],
    scriptPatterns: ['bevy.com', 'bevylabs', 'bevy-'],
    networkDomains: ['api.bevy.com', 'bevy.com'],
    cookiePatterns: ['bevy_', 'bevy'],
    globalPatterns: ['Bevy', 'bevy'],
    formActionPatterns: ['bevy.com'],
    cnamePatterns: ['bevy.com', 'bevylabs.com'],
    htmlPatterns: ['bevy-'],
    metaPatterns: ['bevy'],
  },
  {
    name: 'Hubilo',
    category: 'event',
    domains: ['hubilo.com', 'app.hubilo.com'],
    scriptPatterns: ['hubilo.com', 'hubilo', 'hubilo-'],
    networkDomains: ['api.hubilo.com', 'app.hubilo.com', 'hubilo.com'],
    cookiePatterns: ['hubilo', 'hbl_'],
    globalPatterns: ['hubilo', 'Hubilo'],
    formActionPatterns: ['hubilo.com'],
    cnamePatterns: ['hubilo.com'],
    htmlPatterns: ['hubilo-'],
    metaPatterns: ['hubilo'],
  },
  {
    name: 'EventMobi',
    category: 'event',
    domains: ['eventmobi.com'],
    scriptPatterns: ['eventmobi.com', 'eventmobi'],
    networkDomains: ['api.eventmobi.com', 'eventmobi.com'],
    cookiePatterns: ['eventmobi'],
    globalPatterns: ['EventMobi', 'eventmobi'],
    formActionPatterns: ['eventmobi.com'],
    cnamePatterns: ['eventmobi.com'],
    htmlPatterns: ['eventmobi-'],
    metaPatterns: ['eventmobi'],
  },
  {
    name: 'Goldcast',
    category: 'both',
    domains: ['goldcast.io', 'app.goldcast.io'],
    scriptPatterns: ['goldcast.io', 'goldcast'],
    networkDomains: ['api.goldcast.io', 'goldcast.io'],
    cookiePatterns: ['goldcast'],
    globalPatterns: ['Goldcast', 'goldcast'],
    formActionPatterns: ['goldcast.io'],
    cnamePatterns: ['goldcast.io'],
    htmlPatterns: ['goldcast-'],
    metaPatterns: ['goldcast'],
  },
  {
    name: 'Zuddl',
    category: 'both',
    domains: ['zuddl.com', 'events.zuddl.com', 'app.zuddl.com'],
    scriptPatterns: ['zuddl.com', 'zuddl', 'zuddl-'],
    networkDomains: ['zuddl.com', 'api.zuddl.com', 'events.zuddl.com', 'app.zuddl.com', 'cdn.zuddl.com'],
    cookiePatterns: ['zuddl'],
    globalPatterns: ['Zuddl', 'zuddl'],
    formActionPatterns: ['zuddl.com'],
    cnamePatterns: ['zuddl.com'],
    htmlPatterns: ['zuddl'],
    metaPatterns: ['zuddl'],
  },
  {
    name: 'Whova',
    category: 'event',
    domains: ['whova.com'],
    scriptPatterns: ['whova.com', 'whova'],
    networkDomains: ['whova.com', 'api.whova.com'],
    cookiePatterns: ['whova'],
    globalPatterns: ['Whova', 'whova'],
    formActionPatterns: ['whova.com'],
    cnamePatterns: ['whova.com'],
    htmlPatterns: ['whova-'],
    metaPatterns: ['whova'],
  },
  {
    name: 'SpotMe',
    category: 'event',
    domains: ['spotme.com', 'spot.me'],
    scriptPatterns: ['spotme.com', 'spotme', 'spot.me'],
    networkDomains: ['api.spotme.com', 'spotme.com', 'spot.me'],
    cookiePatterns: ['spotme'],
    globalPatterns: ['SpotMe', 'spotme'],
    formActionPatterns: ['spotme.com'],
    cnamePatterns: ['spotme.com', 'spot.me'],
    htmlPatterns: ['spotme-'],
    metaPatterns: ['spotme'],
  },
  {
    name: 'vFairs',
    category: 'event',
    domains: ['vfairs.com', 'app.vfairs.com'],
    scriptPatterns: ['vfairs.com', 'vfairs'],
    networkDomains: ['api.vfairs.com', 'vfairs.com'],
    cookiePatterns: ['vfairs'],
    globalPatterns: ['vFairs', 'vfairs'],
    formActionPatterns: ['vfairs.com'],
    cnamePatterns: ['vfairs.com'],
    htmlPatterns: ['vfairs-'],
    metaPatterns: ['vfairs'],
  },
  {
    name: 'Socio (Webex Events)',
    category: 'event',
    domains: ['socio.events', 'app.socio.events', 'webexevents.com'],
    scriptPatterns: ['socio.events', 'socio', 'webexevents'],
    networkDomains: ['api.socio.events', 'socio.events', 'webexevents.com'],
    cookiePatterns: ['socio', 'webexevents'],
    globalPatterns: ['Socio', 'socio'],
    formActionPatterns: ['socio.events', 'webexevents.com'],
    cnamePatterns: ['socio.events'],
    htmlPatterns: ['socio-'],
    metaPatterns: ['socio', 'webex events'],
  },
  {
    name: 'Aventri (Stova)',
    category: 'event',
    domains: ['aventri.com', 'stova.io', 'eiseverywhere.com'],
    scriptPatterns: ['aventri.com', 'aventri', 'stova', 'eiseverywhere'],
    networkDomains: ['aventri.com', 'api.aventri.com', 'stova.io', 'eiseverywhere.com'],
    cookiePatterns: ['aventri', 'stova', 'eiseverywhere'],
    globalPatterns: ['Aventri', 'aventri', 'Stova'],
    formActionPatterns: ['aventri.com', 'stova.io'],
    cnamePatterns: ['aventri.com', 'stova.io', 'eiseverywhere.com'],
    htmlPatterns: ['aventri-', 'stova-'],
    metaPatterns: ['aventri', 'stova'],
  },
  {
    name: 'Grip',
    category: 'event',
    domains: ['grip.events'],
    scriptPatterns: ['grip.events', 'grip-event'],
    networkDomains: ['api.grip.events', 'grip.events'],
    cookiePatterns: ['grip_'],
    globalPatterns: ['Grip'],
    formActionPatterns: ['grip.events'],
    cnamePatterns: ['grip.events'],
    htmlPatterns: ['grip-'],
    metaPatterns: ['grip'],
  },
  {
    name: 'Brella',
    category: 'event',
    domains: ['brella.io', 'app.brella.io'],
    scriptPatterns: ['brella.io', 'brella'],
    networkDomains: ['api.brella.io', 'brella.io'],
    cookiePatterns: ['brella'],
    globalPatterns: ['Brella', 'brella'],
    formActionPatterns: ['brella.io'],
    cnamePatterns: ['brella.io'],
    htmlPatterns: ['brella-'],
    metaPatterns: ['brella'],
  },
  {
    name: 'Certain',
    category: 'event',
    domains: ['certain.com'],
    scriptPatterns: ['certain.com'],
    networkDomains: ['api.certain.com', 'certain.com'],
    cookiePatterns: ['certain_'],
    globalPatterns: ['Certain'],
    formActionPatterns: ['certain.com'],
    cnamePatterns: ['certain.com'],
    htmlPatterns: [],
    metaPatterns: ['certain'],
  },
  {
    name: 'Accelevents',
    category: 'event',
    domains: ['accelevents.com'],
    scriptPatterns: ['accelevents.com', 'accelevents'],
    networkDomains: ['accelevents.com'],
    cookiePatterns: ['accelevents'],
    globalPatterns: ['Accelevents'],
    formActionPatterns: ['accelevents.com'],
    cnamePatterns: ['accelevents.com'],
    htmlPatterns: [],
    metaPatterns: ['accelevents'],
  },
  {
    name: 'Sched',
    category: 'event',
    domains: ['sched.com'],
    scriptPatterns: ['sched.com', 'sched-'],
    networkDomains: ['sched.com'],
    cookiePatterns: ['sched_'],
    globalPatterns: ['Sched'],
    formActionPatterns: ['sched.com'],
    cnamePatterns: ['sched.com'],
    htmlPatterns: ['sched-'],
    metaPatterns: ['sched'],
  },
  {
    name: 'Livestorm',
    category: 'webinar',
    domains: ['livestorm.co', 'app.livestorm.co'],
    scriptPatterns: ['livestorm.co', 'livestorm'],
    networkDomains: ['api.livestorm.co', 'livestorm.co'],
    cookiePatterns: ['livestorm'],
    globalPatterns: ['Livestorm', 'livestorm'],
    formActionPatterns: ['livestorm.co'],
    cnamePatterns: ['livestorm.co'],
    htmlPatterns: ['livestorm'],
    metaPatterns: ['livestorm'],
  },
  {
    name: 'Demio',
    category: 'webinar',
    domains: ['demio.com', 'event.demio.com'],
    scriptPatterns: ['demio', 'demio.com'],
    networkDomains: ['api.demio.com', 'event.demio.com', 'demio.com'],
    cookiePatterns: ['demio'],
    globalPatterns: ['Demio', 'demio'],
    formActionPatterns: ['demio.com'],
    cnamePatterns: ['demio.com'],
    htmlPatterns: ['demio'],
    metaPatterns: ['demio'],
  },
  {
    name: 'BigMarker',
    category: 'webinar',
    domains: ['bigmarker.com'],
    scriptPatterns: ['bigmarker'],
    networkDomains: ['bigmarker.com'],
    cookiePatterns: ['bigmarker'],
    globalPatterns: ['BigMarker', 'bigmarker'],
    formActionPatterns: ['bigmarker.com'],
    cnamePatterns: ['bigmarker.com'],
    htmlPatterns: [],
    metaPatterns: ['bigmarker'],
  },
  {
    name: 'GoTo Webinar',
    category: 'webinar',
    domains: ['gotowebinar.com', 'gotomeeting.com', 'goto.com', 'attendee.gotowebinar.com'],
    scriptPatterns: ['gotowebinar', 'gotomeeting', 'goto.com', 'logmeininc.com'],
    networkDomains: ['api.getgo.com', 'gotowebinar.com', 'attendee.gotowebinar.com', 'goto.com'],
    cookiePatterns: ['goto', 'getgo', 'gotowebinar'],
    globalPatterns: ['GoTo', 'gotowebinar'],
    formActionPatterns: ['gotowebinar.com', 'goto.com'],
    cnamePatterns: ['gotowebinar.com'],
    htmlPatterns: ['goto-webinar', 'gotowebinar'],
    metaPatterns: ['gotowebinar'],
  },
  {
    name: 'Zoom Webinar',
    category: 'webinar',
    domains: ['zoom.us', 'us02web.zoom.us'],
    scriptPatterns: ['zoom.us', 'zoom-'],
    networkDomains: ['zoom.us', 'api.zoom.us'],
    cookiePatterns: ['zm_', 'zoom_'],
    globalPatterns: ['ZoomMtg'],
    formActionPatterns: ['zoom.us'],
    cnamePatterns: ['zoom.us'],
    htmlPatterns: ['zoom-'],
    metaPatterns: ['zoom'],
  },
  {
    name: 'Webex',
    category: 'webinar',
    domains: ['webex.com'],
    scriptPatterns: ['webex.com', 'webex'],
    networkDomains: ['webex.com', 'api.webex.com'],
    cookiePatterns: ['webex'],
    globalPatterns: ['Webex', 'webex'],
    formActionPatterns: ['webex.com'],
    cnamePatterns: ['webex.com'],
    htmlPatterns: [],
    metaPatterns: ['webex'],
  },
  {
    name: 'Airmeet',
    category: 'both',
    domains: ['airmeet.com', 'app.airmeet.com'],
    scriptPatterns: ['airmeet.com', 'airmeet'],
    networkDomains: ['api.airmeet.com', 'airmeet.com'],
    cookiePatterns: ['airmeet'],
    globalPatterns: ['Airmeet', 'airmeet'],
    formActionPatterns: ['airmeet.com'],
    cnamePatterns: ['airmeet.com'],
    htmlPatterns: ['airmeet-'],
    metaPatterns: ['airmeet'],
  },
  {
    name: 'BrightTALK',
    category: 'webinar',
    domains: ['brighttalk.com'],
    scriptPatterns: ['brighttalk.com', 'brighttalk'],
    networkDomains: ['api.brighttalk.com', 'brighttalk.com'],
    cookiePatterns: ['brighttalk'],
    globalPatterns: ['BrightTALK', 'brighttalk'],
    formActionPatterns: ['brighttalk.com'],
    cnamePatterns: ['brighttalk.com'],
    htmlPatterns: ['brighttalk-'],
    metaPatterns: ['brighttalk'],
  },
  {
    name: 'WordPress',
    category: 'both',
    secondary: true,
    domains: [],
    scriptPatterns: ['wp-content', 'wp-includes', 'wp-json'],
    networkDomains: [],
    cookiePatterns: ['wordpress_', 'wp-'],
    globalPatterns: ['WordPress'],
    formActionPatterns: [],
    cnamePatterns: [],
    htmlPatterns: ['wp-content'],
    metaPatterns: ['WordPress'],
  },
  {
    name: 'Webflow',
    category: 'both',
    secondary: true,
    domains: ['webflow.io'],
    scriptPatterns: ['webflow.com', 'assets-global.website-files.com'],
    networkDomains: ['webflow.com'],
    cookiePatterns: [],
    globalPatterns: ['Webflow'],
    formActionPatterns: [],
    cnamePatterns: ['webflow.io'],
    htmlPatterns: [],
    metaPatterns: ['webflow'],
  },
];
